# Nombre de la aplicación
spring.application.name=product

# Path para consulta de documentación de API con OpenAPI UI
springdoc.swagger-ui.path=/documentation.html

# Path para acceso a documentación de API
springdoc.api-docs.path=/api-docs

# Método de ordenamiento de operaciones
springdoc.swagger-ui.operationsSorter=method