# Nombre de la aplicación
spring.application.name=product

# Dirección de acceso a la DB
spring.datasource.url=jdbc:mysql://localhost:3306/db_name

# Usuario de la DB
spring.datasource.username=db_user

# Contraseña de la DB
spring.datasource.password=db_password

# Nombre del driver
spring.datasource.driverClassName=com.mysql.jdbc.Driver

# Path para consulta de documentación de API con OpenAPI UI
springdoc.swagger-ui.path=/documentation.html

# Path para acceso a documentación de API
springdoc.api-docs.path=/api-docs

# Método de ordenamiento de etiquetas
springdoc.swagger-ui.tags-sorter=alpha

# Método de ordenamiento de operaciones
springdoc.swagger-ui.operationsSorter=method

# Tipo de expansión a operaciones al iniciar
springdoc.swagger-ui.doc-expansion=none

# Ruta del directorio para almacenar imagenes de producto
app.upload.dir=uploads